cn:
  location: "地点："
  you-can-also: "您也可以："
  donate: "捐赠"
  time: "每周五 8-9 PM（PT）"
  performance: "演出："
  buy-tickets: "购票"
  except-holidays: "，公共假期前除外"
en:
  except-holidays: ", except public holidays"
  buy-tickets: "Buy Tickets"
  donate: "Donate"
  time: "Every Friday 8-9 PM (PT)"
  location: "Location: "
  performance: "Open-mic: "
  you-can-also: "You can also: "
